// <auto-generated />
using dtso.data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace dtso.data.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dtso.data.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AnnualBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Money")
                        .HasDefaultValue(0m);

                    b.Property<string>("Description");

                    b.Property<int>("RegionalAccountCodeId");

                    b.Property<int?>("ShredNo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(-1);

                    b.Property<int?>("SubNo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(-1);

                    b.HasKey("AccountId");

                    b.HasIndex("RegionalAccountCodeId", "SubNo", "ShredNo")
                        .IsUnique()
                        .HasFilter("[SubNo] IS NOT NULL AND [ShredNo] IS NOT NULL");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("dtso.data.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("InvoiceDate");

                    b.Property<int>("InvoiceTypeId");

                    b.Property<int>("VendorId");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceTypeId");

                    b.HasIndex("VendorId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("dtso.data.Entities.InvoiceAccount", b =>
                {
                    b.Property<int>("InvoiceId");

                    b.Property<int>("AccountId");

                    b.Property<decimal>("Expense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Money")
                        .HasDefaultValue(0m);

                    b.HasKey("InvoiceId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("InvoiceAccounts");
                });

            modelBuilder.Entity("dtso.data.Entities.InvoiceType", b =>
                {
                    b.Property<int>("InvoiceTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("InvoiceTypeId");

                    b.ToTable("InvoiceType");
                });

            modelBuilder.Entity("dtso.data.Entities.RegionalAccountCode", b =>
                {
                    b.Property<int>("RegionalAccountCodeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountNumber");

                    b.Property<string>("AccountPrefix")
                        .IsRequired();

                    b.Property<int>("DeptartmentNumber");

                    b.Property<int>("FundNumber");

                    b.Property<string>("ProjectDescription");

                    b.Property<string>("ProjectNumber")
                        .IsRequired();

                    b.HasKey("RegionalAccountCodeId");

                    b.ToTable("RegionalAccountCodes");
                });

            modelBuilder.Entity("dtso.data.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<DateTime?>("ContractEnd");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("ContractStart");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(12);

                    b.Property<string>("PointOfContact");

                    b.Property<string>("State");

                    b.Property<string>("Website");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(8);

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("dtso.data.Entities.Account", b =>
                {
                    b.HasOne("dtso.data.Entities.RegionalAccountCode", "RegionalAccountCode")
                        .WithMany()
                        .HasForeignKey("RegionalAccountCodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("dtso.data.Entities.Invoice", b =>
                {
                    b.HasOne("dtso.data.Entities.InvoiceType", "InvoiceType")
                        .WithMany()
                        .HasForeignKey("InvoiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("dtso.data.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("dtso.data.Entities.InvoiceAccount", b =>
                {
                    b.HasOne("dtso.data.Entities.Account", "Account")
                        .WithMany("InvoiceAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("dtso.data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceAccounts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
